### ISSUE TITLE
Make script updateable without having to care for the variables to keep it running

### ISSUE THREAD

**Issue by SantosSi** [Nozzie/kvm-borg-backup#1]
Separating code from configuration makes sense in this case.

**Comment by SantosSi** [comment]
It might make sense to carve the parameter definition out into a file of its own (with a template shipped), so that the code can be updated without having to adapt hard-coded script parameters to the own conditions over and over.

**Comment by Nozzie** [comment]
In reality, how often do you need to update this script? Once configured, it just works.

It should be easy to accomplish yourself, all the config stuff is in the top part of the script, just save it in a different file and import it in the 'code' file with "source config_file"

**Comment by SantosSi** [comment]
This is about a way to improve the script's support process.

Well, your suggestion matches what came to my mind as a solution. If you don't want to implement the solution you described: Not sure if I have the rights to push such changes to your project, so I started with the issue as a first step.

**Comment by Nozzie** [comment]
Thanks for the suggestion, but personally I think is is a neater solution to have everything in one file.

If you want to change stuff that will also be available to others, you can just fork the project. Then you can change anything you want.
