### ISSUE TITLE
Incompatible with parameter: --pool images

### ISSUE THREAD

**Issue by SantosSi** [Nozzie/kvm-borg-backup#2]
The parameter `--pool images` causes it to not run on my setup. After removing it is fine for me.

**Comment by Nozzie** [comment]
I will have to look into this. I have no idea if it runs for me without the parameter.

**Comment by slankes** [comment]
Same here (on Fedora 37). There is no pool called images on my system so it fails. Removing `--pool images` fixes that.

**Comment by Nozzie** [comment]
Can you give me the output of `virsh pool-list` on your system?
For me it is:
```
 Name     State    Autostart
------------------------------
 images   active   yes
```

**Comment by slankes** [comment]
Sure:

```
[root@gate ~]# virsh pool-list
 Name            State    Autostart
-------------------------------------
 default         active   yes
 libvirtimages   active   yes
 nvram           active   yes
```

**Comment by Nozzie** [comment]
I don't see any reason the --pool should be specified at all. I'll remove it form the script.
